spring:
  application:
    name: homeworkCrud

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newschema
    username: root
    password: lhs0324*

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
